### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by CharlieMallon** [HackathonBITeam10/silverconnections#10]
Create the index HTML, header and footer.

**Comment by fabiodearaujo** [comment]
Created Index.html with structure.

**Comment by fabiodearaujo** [comment]
Created Header with Title and Introduction/directions of use.

**Comment by fabiodearaujo** [comment]
Created directory tree structure including style.css file on it.

**Comment by fabiodearaujo** [comment]
Merged and pushed code to the master.
