### ISSUE TITLE
Create Milestones for the Project

### ISSUE THREAD

**Issue by fabiodearaujo** [HackathonBITeam10/silverconnections#18]
Hello @brimurphy @KirstChat @Craig-Ryan @CharlieMallon - I discovered that we can also create Milestones for the Prject. Please include here when on Monday we can decide the Milestones to be included.
Maybe at the same 13:00 Irish time (7am to Craig).
Please share your toughts.

**Comment by CharlieMallon** [comment]
We could do, 

Project Definition.
Project Scope.
Wireframes and Site Architecture. 
Visual Design.
Site Development.
Site Testing.
Launch.
presentation?

**Comment by fabiodearaujo** [comment]
Hi @CharlieMallon , I agree with your milestones. Is someone free to take up this task to create the milestones? @brimurphy @KirstChat @Craig-Ryan

**Comment by KirstChat** [comment]
I still need to finish getting screenshots and writing up the steps for the ZOOM and WhatsApp pages. If I get those finished by this evening (I have some other work related stuff I need to do) I'm happy to help.

**Comment by fabiodearaujo** [comment]
Milestnes were discovered late in the process. We will remember to create the milestones next time we participate in a project.
