### ISSUE TITLE
Task - initial wireframes

### ISSUE THREAD

**Issue by CharlieMallon** [HackathonBITeam10/silverconnections#2]
Task - everyone to jot down some initial wire frames and attach them in the comments.

You don't have to design a whole site, it can just be a feature or page.

We will meet at 1300 (or 0700) on the 3rd to discuss.

**Comment by CharlieMallon** [comment]
[Wireframe - CM.pdf](https://github.com/HackathonBITeam10/silverconnections/files/4866976/Wireframe.-.CM.pdf)

Here are my first Ideas on wire frame speak to you tomorrow :)

**Comment by fabiodearaujo** [comment]
![mobilewireframefabio](https://user-images.githubusercontent.com/52252478/86462613-c4b62d80-bd23-11ea-849d-591cae4a6cf9.PNG)
![desktopwireframe fabio](https://user-images.githubusercontent.com/52252478/86462616-c54ec400-bd23-11ea-8da5-5346a87402ae.PNG)

Uploading my version of Desktop and Mobile view.

**Comment by KirstChat** [comment]
[SIlver Connections.pdf](https://github.com/HackathonBITeam10/silverconnections/files/4869568/SIlver.Connections.pdf)

**Comment by fabiodearaujo** [comment]
In the call was decided that Kirsty wireframe will be the base to our website.
