### ISSUE TITLE
the link only works if you click the text

### ISSUE THREAD

**Issue by CharlieMallon** [HackathonBITeam10/silverconnections#29]
we want the link to work if we click the card

**Comment by CharlieMallon** [comment]
code needs to be changed to be structured like this

```
<a class="card" href="zoom-download.html">
       <div>
            <h3>How to Download Zoom</h3>
       </div>
</a>
```

thank @fabioaraujo76 

when you have changed your 'area' please comment here

**Comment by fabiodearaujo** [comment]
I fixed the links on index html and all pages for skype.

**Comment by CharlieMallon** [comment]
fixed for facetime.html

**Comment by KirstChat** [comment]
Fixed on zoom.html. Just need to push. Adding some images first.
