### ISSUE TITLE
User Stories

### ISSUE THREAD

**Issue by CharlieMallon** [HackathonBITeam10/silverconnections#3]
User stories for
 - 1st time Visitor Goals (New User)
 - returning Visitor Goals
 - frequent Visitor Goals

**Comment by CharlieMallon** [comment]
![image](https://user-images.githubusercontent.com/63316180/86477356-297f8100-bd40-11ea-909d-60e31530127b.png)

**Comment by Craig-Ryan** [comment]
Returning Visitors Goals:
As a returning visitor, I want to review the steps on how to use the technologies on this site.

**Comment by CharlieMallon** [comment]
![image](https://user-images.githubusercontent.com/63316180/86477773-0b665080-bd41-11ea-85de-085d6a6c095f.png)

**Comment by Craig-Ryan** [comment]
3. As a frequent user I want to be able to find out about new technologies added to the list in the how to section.
