### ISSUE TITLE
Check Facetime Content / format

### ISSUE THREAD

**Issue by CharlieMallon** [HackathonBITeam10/silverconnections#30]
Hey can someone check my content / format, make sure it all makes sense.

**Comment by fabiodearaujo** [comment]
Hi Charlie, maybe would be ok if you create a 4th card so we keep the design similar. Could be some extras.
Also I noticed it is needed to update the links so the area clickable is the full card.
Buttons also should be updated.
Talk to you in the morning.

**Comment by fabiodearaujo** [comment]
I fixed the buttons that are now beside each other.
