### ISSUE TITLE
iframe videos needs to be responsive

### ISSUE THREAD

**Issue by fabiodearaujo** [HackathonBITeam10/silverconnections#35]
Noticed a bug on the youtube videos included on Facetime.

on the width property we should try to use % instead of pixels. try to change it to 90%  or 95% and check how it respond.

The attributes were on the HTML instead of CSS file. If anyone feel comfortable, can be created a class and include the width and height for every video on the Style.CSS.

**Comment by CharlieMallon** [comment]
create a class to set % width - remove from the iframe.

**Comment by CharlieMallon** [comment]
@fabioaraujo76 added the video class to css.  class added to all ifmes using a div (see example below)
`<div class="video">
                    <iframe src="https://www.youtube.com/embed/mAD1B_dw1_Y" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                </div>`

Not the height and width have been removed from the iframe
