### ISSUE TITLE
Start Read me

### ISSUE THREAD

**Issue by CharlieMallon** [HackathonBITeam10/silverconnections#4]
- Reasoning for choices
     - Big Buttons
     - large writing
- Colour scheme & typography 
    - contrasting colours
    - bright colours?
- Include the User stories

**Comment by CharlieMallon** [comment]
https://github.com/Code-Institute-Solutions/SampleREADME

**Comment by CharlieMallon** [comment]
Use K's wire frame for the idea.  I will put some mobile wire frames based on her ideas.

**Comment by Craig-Ryan** [comment]
Include color, typography and imagery til later on when a design is made.
