### ISSUE TITLE
Design Choices

### ISSUE THREAD

**Issue by CharlieMallon** [HackathonBITeam10/silverconnections#5]
Colour scheme
    - contrasting colours
    - bright colours?

Typography 
  - Size
  - Style

**Comment by brimurphy** [comment]
![Silver Connections](https://user-images.githubusercontent.com/50965607/86517051-b0eef200-be1d-11ea-96ce-68a86b3020d7.png)

Heres what I'm thinking for the design aspect, 

fonts: Headers - Merriweather 700    Normal Text - Noto Serif 400     Buttuns - Ubuntu ;
font size: 1em = 18px
word spacing = 2em

colors: 
platinum #e8e9eb, 
blood red #660000, (contrast with platinum 11:1)
blue #0a2342 (contrast with platinum 13:1)
yellow #ffffcc
(just thinking either blue or red not both).

As for features I taught a button that could increase/decrease the font size on the page would be cool
also a button like Fabio had on his Space Station project to invert the colours would be good too.

**Comment by fabiodearaujo** [comment]
Here is the Index.html following @KirstChat wireframe:
![landingpage](https://user-images.githubusercontent.com/52252478/86522426-54a7c480-be55-11ea-910d-08821148dae9.png)

Please leave your opinion around the colors, I chose grey-scale tons to don't mess up too much with the colorful icons.

**Comment by CharlieMallon** [comment]
@brimurphy, For the colour choices, i think:

- the red looks retro
- the dark, i like but may not appeal to the demographic we are catering to (as it doesn't look like a web page).
- the blue looks good

inverting colours on buttons makes it clear what is being selected and i like this.

**Comment by KirstChat** [comment]
I would say a white background for the cards is a good idea with black or dark grey text. It’s easy to read then. Might be worth taking into consideration what effect different colours have on people. So red is danger, yellow is happy etc. Probably worth going with colours that are positive and encouraging 👍 it’s worth a google search but I’ve found this: https://www.creativebloq.com/web-design/12-colours-and-emotions-they-evoke-61515112 is it also worth adding a home button somewhere for users to return to the home page?

**Comment by fabiodearaujo** [comment]
Hello everyone, Just a detail. All images of the icons has white background, I can try to edit them to put another color if necessary, but I don't know how the contrast would be with the icon colours. I am posting here just some of the tries I did using the background suggested:

Background: Yellow, Cards: Platinum, Font color: Very dark blue from initial post:
![image](https://user-images.githubusercontent.com/52252478/86542289-5ed8ca00-bf0c-11ea-88f9-14d5db1f7bcf.png)

**Comment by fabiodearaujo** [comment]
This one was using a not so bright Green to create the contrast with the white cards:
Background: #8cc59d - Cards: white - Font: Black

![image](https://user-images.githubusercontent.com/52252478/86542385-4917d480-bf0d-11ea-8115-cbf8c8df5f61.png)

**Comment by fabiodearaujo** [comment]
This last one maintaining the cards white and font black but with background blue to give the contrast: 
Background: #89bad2

 
![image](https://user-images.githubusercontent.com/52252478/86542441-af9cf280-bf0d-11ea-9b50-1f8ca2e3747e.png)

**Comment by brimurphy** [comment]
I actually prefer your orignal colour with the grey on white Fabio. I've tried a few colours and the only one I liked other than that was the dark blue as a background. but as Charlie said I don't think it works for the audience we're aiming it at.

![Screenshot (31)](https://user-images.githubusercontent.com/50965607/86543135-c9d9cf00-bf13-11ea-9fcd-e0f4c5e39949.png)

Not sure why it's displaying as 3 and 1 underneath for me either.

**Comment by fabiodearaujo** [comment]
> Not sure why it's displaying as 3 and 1 underneath for me either.

This is because it is responsive, if your screen get bigger that will include the 4th card also, but this can change. I did this initial page only to have a base start and also visual of what can it be.

My screen is 1080p, it fits all cards if I open all the way:

![image](https://user-images.githubusercontent.com/52252478/86543628-5090ab00-bf18-11ea-92b2-3ea61fd5324a.png)

**Comment by CharlieMallon** [comment]
I like either the green or the lighter blue

**Comment by fabiodearaujo** [comment]
In a group call was decided the light blue background was the best choice to our target audience.
