### ISSUE TITLE
Content - Skype

### ISSUE THREAD

**Issue by CharlieMallon** [HackathonBITeam10/silverconnections#6]
step by steps and find a good video for;

How to place a call
How to revive a call
What the buttons do
How to sign up for an account

**Comment by fabiodearaujo** [comment]
Found some Videos, sharing here to be decided which one to use:
https://www.youtube.com/watch?v=_FSoTzjZfHg

https://www.youtube.com/watch?v=bW54GV_F16E

https://www.youtube.com/watch?v=z6AsrQYv5wQ

https://www.youtube.com/watch?v=mkVW89-4RP4

https://www.youtube.com/watch?v=rVcVC1FlGCw

https://www.youtube.com/watch?v=TgcEfK6wCTo

https://www.youtube.com/watch?v=NRcb3uB3Jac

Unfortunately on Skype own account on Youtube there are very little videos of how to use.

**Comment by fabiodearaujo** [comment]
Hello All, 
Could everyone check the videos and give an opinion on which one we should use?
Thank you :)

**Comment by brimurphy** [comment]
Hey Fabio, had a quick look at the videos just now here's what I taught

> https://www.youtube.com/watch?v=_FSoTzjZfHg --Too long
> 
> https://www.youtube.com/watch?v=bW54GV_F16E --Detailed but I didn't feel it, bit of an echo.
> 
> https://www.youtube.com/watch?v=z6AsrQYv5wQ --Seems it's for mobile instalss only
> 
> https://www.youtube.com/watch?v=mkVW89-4RP4 --Easy to follow and aimed at seniors #techsavyseniors is qouted in it
> 
> https://www.youtube.com/watch?v=rVcVC1FlGCw --Very simple to follow instructions with pics, nicely paced, only 3.5mins 
> 
> https://www.youtube.com/watch?v=TgcEfK6wCTo --Starts like an add for the first 45secs, doesn't show how to sign up.
> 
> https://www.youtube.com/watch?v=NRcb3uB3Jac --Very informative but the instructor might be talking too quickly for seniors

I'd recommend the 4th or 5th video, hope this helps.

**Comment by fabiodearaujo** [comment]
Thank you @brimurphy for the detailed information. 👍

**Comment by fabiodearaujo** [comment]
Content also being created by myself.  I will think about the video as it is a third party.
