### ISSUE TITLE
Content - Zoom

### ISSUE THREAD

**Issue by CharlieMallon** [HackathonBITeam10/silverconnections#7]
step by steps and find a good video for;

How to place a call
How to revive a call
What the buttons do
How to sign up for an account

**Comment by KirstChat** [comment]
A lot of the ZOOM video tutorials are pretty long and aimed at teachers, students and more tech savvy people. This is what I've got so far...

Short sign-up and download video from official ZOOM channel: https://www.youtube.com/watch?v=qsy2Ph6kSf8
Joining a meeting from official ZOOM channel: https://www.youtube.com/watch?v=-s76QHshQnY

Videos similar to WhatsApp tutorial: https://www.youtube.com/watch?v=-s76QHshQnY 
https://www.youtube.com/watch?v=POyXj9NR7FY&t=200s

How to download and install on Windows: https://www.youtube.com/watch?v=DzgrQ14xyuo

How to download and install on Mac: https://www.youtube.com/watch?v=D9tTuSNgo7k

I'll write a step by step guide today and get some screenshots

**Comment by KirstChat** [comment]
Link to download ZOOM: https://zoom.us/download

**Comment by KirstChat** [comment]
I've been building a step by step guide based around these:

http://www.arrowseniorliving.com/wp-content/uploads/2020/04/2020-ASL-Resident-Zoom-Guide-01b.pdf

**Comment by KirstChat** [comment]
[ZOOM Step by Step Guide.txt](https://github.com/HackathonBITeam10/silverconnections/files/4884190/ZOOM.Step.by.Step.Guide.txt)
Need to find more screenshots...
![zoom-home-screen](https://user-images.githubusercontent.com/55391534/86767886-964a9200-c044-11ea-8914-f00e35b0a8cf.png)
![zoom-meeting-id](https://user-images.githubusercontent.com/55391534/86767892-98acec00-c044-11ea-98b5-c69a5949ea96.png)
![zoom-sign-in](https://user-images.githubusercontent.com/55391534/86767895-98acec00-c044-11ea-9b9b-d164c820ffab.png)
