### ISSUE TITLE
Messaging service

### ISSUE THREAD

**Issue by CharlieMallon** [HackathonBITeam10/silverconnections#9]
step by steps and find a good video for;

How to place a call
How to revive a call
What the buttons do

**Comment by brimurphy** [comment]
Here's what I've got on FB messenger:

[How to use Facebook Messenger.txt](https://github.com/HackathonBITeam10/silverconnections/files/4875677/How.to.use.Facebook.Messenger.txt)


https://youtu.be/SAmOfkn1Tfg

**Comment by KirstChat** [comment]
I've found a couple of short videos explaining how to signup for WhatsApp and how to use it. I just need to write up a step by step guide and get some screen shots.

How to download and install: https://www.youtube.com/watch?v=fZsJ6WH9C0c&list=PLk3xjyeTggSacPdub--Q4grk7rxZMqMSu&index=2

How to create an account: https://www.youtube.com/watch?v=k-vm46ldvhI&list=PLk3xjyeTggSacPdub--Q4grk7rxZMqMSu&index=3

How to use WhatsApp: https://www.youtube.com/watch?v=0vJhIX8Gq54&list=PLk3xjyeTggSacPdub--Q4grk7rxZMqMSu&index=4

**Comment by KirstChat** [comment]
WhatsApp screenshots taken from here: https://www.businessinsider.com/how-to-use-whatsapp-on-iphone?r=US&IR=T

**Comment by KirstChat** [comment]
How to verify your phone number on WhatsApp: https://www.youtube.com/watch?v=AWemFbRf95g&feature=emb_title

**Comment by KirstChat** [comment]
[WhatsApp Step by Step Guide.txt](https://github.com/HackathonBITeam10/silverconnections/files/4883846/WhatsApp.Step.by.Step.Guide.txt)
![whatsapp-chat](https://user-images.githubusercontent.com/55391534/86756775-8c239600-c03a-11ea-8bf3-e0ef8939e431.jpeg)
![whatsapp-message](https://user-images.githubusercontent.com/55391534/86756780-8cbc2c80-c03a-11ea-9581-d12627bfcdf8.jpeg)
![whatsapp-name](https://user-images.githubusercontent.com/55391534/86756784-8ded5980-c03a-11ea-8db8-84004edc4f8b.jpeg)
![whatsapp-number](https://user-images.githubusercontent.com/55391534/86756787-8e85f000-c03a-11ea-9986-07091a628536.jpeg)
![whatsapp-welcome](https://user-images.githubusercontent.com/55391534/86756790-8e85f000-c03a-11ea-9e1b-6e3a2d3eb65e.jpeg)
![app-store](https://user-images.githubusercontent.com/55391534/86757150-d4db4f00-c03a-11ea-8d00-349a35c2b44c.jpeg)
![play-store](https://user-images.githubusercontent.com/55391534/86757152-d573e580-c03a-11ea-8fa6-e6cb1114066b.png)
